# Generated by Django 3.2.8 on 2022-04-22 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("runner", models.CharField(default="", max_length=30)),
                (
                    "location",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("run", models.CharField(max_length=30)),
                ("runner", models.CharField(max_length=30)),
                ("index", models.IntegerField(default=0)),
                (
                    "time",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("elevation", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
