# Generated by Django 3.2.8 on 2022-03-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.run')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.runner')),
            ],
        ),
    ]
